version: '3.8'

services:
  # Nosso serviço de API (será criado depois, opcional para agora)
  # api: ...

  # Serviço de banco de dados agora usando PostgreSQL
  db:
    image: postgres:15-alpine # Imagem oficial e leve do PostgreSQL
    container_name: postgres_estoque_db
    restart: always
    ports:
      # A porta padrão do PostgreSQL é 5432
      - "5432:5432"
    environment:
      # O PostgreSQL usa variáveis diferentes do MySQL
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # Senha para o desenvolvimento local
      POSTGRES_DB: estoque_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: